---
# tasks file for ansible_incron
- name: Fetch OS 
  include: debian.yml
  when: ansible_os_family == "Debian"

- name: Fetch OS
  include: redhat.yml
  when: ansible_os_family == "RedHat"

- name: include config file
  include: config.yml

