---
# tasks file for ansible_incron
- name: Fetch OS 
  import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Fetch OS
  import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: include config file
  import_tasks: config.yml

