---
- name: Add epel in Centos
  yum: name=epel-release state=present

- name: Updating cache ...
  yum: name=* state=latest

- name: Install incron in Centos
  yum: name={{ item }} state=present
  with_items:
      - libselinux-python
      - incron

- name: Ensure Incron is running and enabled as configured.
  service:
    name: "{{ incron_daemond }}"
    state: started
    enabled: yes
  when: incron_enabled

- name: Ensure Incron is stopped and disabled as configured.
  service:
    name: "{{ incron_daemond }}"
    state: stopped
    enabled: no
  when: not incron_enabled

